### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by customcommander** [avast/safariextz#1] opened 2015-08-11 09:44 UTC
Hey guys,

First off thanks for this npm module! However I've been trying to get this working for a few days without any success.

Before explaining the steps I went through, can you guys still build a Safari extension using this? I've read a lot of posts about `xar 1.6.1` and how to use it to package and sign a `.safariextz` but they're all two years old now and I've got the feeling that Apple might just have changed the way this should be done, superseding everything I've read or been trying to do so far.

Cheers,

**Comment by pavelstudeny** [comment] 2015-08-11 19:11
Yeah, we are still using it, although the two years old xar 1.6.1 might crash on Windows depending on the data you are packing. It works OK on Linux and Mac.
I'm not sure what exactly your problem is. It might take a bit of effort to get rid of the default version (1.5 or 1.7) on some systems. I suggest to run xar from the command line and make sure the version is 1.6.1 (only then it supports the extra arguments).

**Comment by customcommander** [comment] 2015-08-11 19:53
Yay! :smiley:  

I'm using `xar 1.6.1` but as I didn't want to override the existing `xar 1.7` on my machine (Mac OS X) I have compiled it using a specific path (see this [gist](https://gist.github.com/kilfu0701/8e0ee7e856d1960c7ff9)). I had to hack your module a bit so that it can accepts a different path to `xar`.

I know for sure that it is using `xar 1.6.1` and the `safariextz` package is built. Here's the code used:

``` javascript
#!/usr/bin/env node

var safariextz = require('safariextz');

var p = '/Users/gonzalesj/Code/importer';

safariextz(p+'build-output/importer.safariextz', p+'build-output/importer.safariextension/', {
    privateKey: p+'tmp/key.pem',
    extensionCer: p+'tmp/dev.cer',
    appleDevCer: p+'tmp/apple1.cer',
    appleRootCer: p+'tmp/apple2.cer',
    temp: '/tmp'
});
```

Note: I've used the apple certificates shipped with your module as well as those existing on my machine (I've exported the two apple certificates present in my keychain to `.cer` files).

Unfortunately when I try to install the package I get this error:

<img width="532" alt="screen shot 2015-08-11 at 20 47 50" src="https://cloud.githubusercontent.com/assets/681975/9208252/55ea923c-406a-11e5-9ca2-560cff095e8e.png">

Thanks for your help.

**Comment by pavelstudeny** [comment] 2015-08-12 08:20
So no error, everything gets packed and then it doesn't install. Might be a problem with the certificates, they are quite tricky. I suggest the following:
1. I assume that when you open the extension builder in Safari, it doesn't complain about a missing developer certificate (and that's the one you are using with safariextz) and your extension normally builds and runs from there. Does the size of the extension packages built by Safari and safariextz roughly match?
2. check the format:
3. privateKey starts with -----BEGIN PRIVATE KEY-----
4. extensionCer is a binary file that contains your account email
5. appleDevCer is a binary file that contains Apple Worldwide Developer Relations Certification Authority
6. appleRootCer is a binary file that contains Apple Certification Authority

**Comment by robertknight** [comment] 2015-08-12 16:02
I can reproduce the same issue. I've verified steps 2 to 6 from the above Some additional info:
- Dumping the certificates from a working extension created by extension builder and a non-working extension created by safariextz produces byte-identical files.
- Comparing the dumped XML TOC from the working/non-working extension shows extra metadata in the TOC file from the non-working file for extended attributes (user, mode etc.) which are not present in the Extension Builder created extension. The files and directories for both extensions are the same in ways that are obviously important though: Same names, checksums, file sizes, compression methods - this is a trivial test extension using the "Hello World" example in the Safari documentation.

There is a significant difference in the file size however. The "Hello World" extension created by safariextz is 4.9KB, the one created by extension builder is 8.2KB. 

My system is running the Safari 9 Beta, in case that's relevant.

**Comment by customcommander** [comment] 2015-08-12 17:47
> I assume that when you open the extension builder in Safari, it doesn't complain about a missing developer certificate (and that's the one you are using with safariextz) and your extension normally builds and runs from there. Does the size of the extension packages built by Safari and safariextz roughly match?

Correct. The extension builder can see my developer certificate and as far as I am aware it's also the one  that I'm using with safariextz. Also ran check 2-6 and can't see anything wrong.

I thought that maybe the Apple's certificates were out of date but if compare yours (apple1.cer + apple2.cer shipped with your module) and those [mentioned here](https://github.com/Rob--W/extension-dev-tools/tree/master/safari#building-automated-linuxmac) they are identical.

So perhaps my personal developer certificate is the issue here but I don't know of any simple way to confirm this.

I once noticed the size difference that @robertknight mentions. In my last attempt (few minutes ago) the two artefacts (one from Apple's extension builder and one from your module) are about the same size.

Are you using a developer certificate issued a long time ago?

Could you share a sample of a build script using this module?

Thanks guys.

**Comment by robertknight** [comment] 2015-08-12 19:19
The extra data I mentioned occurs at the end of the archive, after the compressed data for the last file. Safari will still open and install the extension if it is truncated after the end of the compressed data for the last file in the archive, where the xar file is expected to end.

**Comment by pavelstudeny** [comment] 2015-08-12 19:54
We are in the process of getting new certificates (the ones we have are about half a year old, even before the change from free to paid). I will re-test once we have them. It should be in a few days.

In the meantime, it would be great if you found some older certificates for a comparison.

**Comment by robertknight** [comment] 2015-08-14 20:20
I was able to generate a safariextz archive with a signature that Safari accepts by signing the compressed TOC data using 'openssl dgst -sign' rather than 'openssl rsautl ...'  which is what this package currently uses. The difference is explained [here](http://stackoverflow.com/a/16264508). Briefly, 'openssl dgst' ASN.1 encodes the hash before signing it, whereas 'openssl rsautl' doesn't.

This was done with OS X 10.10 and Safari 9.0. The xar tool doesn't have a facility to dump the raw compressed TOC data from the xar archive, so I wrote a tool for that myself. I'll get the code for that tidied up and post it.

**Comment by robertknight** [comment] 2015-08-14 20:40
> The xar tool doesn't have a facility to dump the raw compressed TOC data from the xar archive, so I wrote a tool for that myself. I

Ah, I'm mistaken, I missed the `--dump-toc-raw` option

**Comment by pavelstudeny** [comment] 2015-08-15 09:34
Impressive! I will cross-check this against Safari 8 and pull the changes until 2015-08-18.

**Comment by pavelstudeny** [comment] 2015-08-17 14:51
Robert, I assume that the pull request still requires the xar fix https://github.com/robertknight/xar/commit/847103b787cfddf200c61d7d93fb57f993bdd976 . May I suggest that you increase the xar version number to 1.6.2 so that people don't get confused which one to use? Unless mackyle is going to do that himself.

**Comment by robertknight** [comment] 2015-08-17 16:48
@pavelstudeny yes it currently does. I'll bump the patch version as you suggested.

An alternative approach I started to look into was replacing the xar tool with something else entirely to avoid the hassle of fetching, building and installing a custom build of xar. The format isn't that complicated, so using something like [node-ctype](https://github.com/rmustacc/node-ctype) it might be possible to have something with no external dependencies.

**Comment by pavelstudeny** [comment] 2015-08-18 10:57
@robertknight , seems that the fix from https://github.com/robertknight/xar/commit/847103b787cfddf200c61d7d93fb57f993bdd976 (both this package and xar) produce packages that won't install into Safari 8.

I don't think there would have to be two extension versions, for Safari 8 and Safari 9 (but maybe that's the case), so this will require a deeper investigation.

Getting rid of xar might be a good idea. The Safari extension packing support in 1.6.1 looks more like a hack, since this functionality is missing again in xar 1.7. Please let me know how it goes.

**Comment by robertknight** [comment] 2015-08-18 11:45
Thanks for testing. I'll continue investigating further.

**Comment by customcommander** [comment] 2015-08-21 12:03
You guys are legends! 😍

**Comment by robertknight** [comment] 2015-08-23 11:14
@pavelstudeny - I was able to install an extension created using the PR to safariextz (https://github.com/avast/safariextz/pull/2) plus the patch to xar referenced in that PR in Safari 8.0.8 under OS X Yosemite.

Can you try installing this extension on your system and report whether Safari accepts it: https://www.dropbox.com/s/bgmq645zwde72z8/testextension.safariextz?dl=0

When installed this extension adds a very simple toolbar to Safari.

If that extension doesn't install on your system, can you report the exact versions of Safari and OS X that you are using?

**Comment by pavelstudeny** [comment] 2015-08-24 16:18
Yeah, the testextension works well - it might have been a problem on my side when testing it, especially since I tried to build the extension on Windows with xar built via cygwin. I'm sorry about that - will retry.

**Comment by pavelstudeny** [comment] 2015-08-25 14:41
I have built robertknight/xar on a Mac, applied the patch to safariextz, the extension size is about right and I still can't install the extension. Safari 8.0.6, MacOS 10.10.3.
It seems that the old way probably works with the old certificates and the new way with the new certificates. I'll check whether the certificate types can be recognised automatically.

@robertknight , seems that mackyle isn't very responsive about your xar patch. Once I make a new safariextz release, I will redirect to your fork, if you manage to make it a 1.6.2 release (or rewrite it into JavaScript). It would be great to have Windows, Linux and Mac binaries somewhere.

**Comment by robertknight** [comment] 2015-08-25 21:20
> It seems that the old way probably works with the old certificates and the new way with the new certificates.

Can you post the full public certificate chain that you are using? Or a link to a xar file from which I can dump the cert chain? Then it should be possible to compare to the test extension above and see where they differ.

> Once I make a new safariextz release, I will redirect to your fork, if you manage to make it a 1.6.2 release (or rewrite it into JavaScript). 

I made a start on the rewrite-it-in-JavaScript approach, hoping to get that into a usable state this week.

**Comment by pavelstudeny** [comment] 2015-08-27 14:01
I have verified that when duping certificates (xar --extract-certs) from an extension created directly by Safari 9 beta (that then installs well) and by safariextz (that doesn't install), the certificates are the same. The two Apple certificates remain the same for me as those at https://github.com/avast/safariextz/tree/master/apple.

Neither extensions created by the current safariextz release and by the patch robertknight/xar@847103b work for me in Safari 9 beta, and neither with the half a year old developer certificate nor with a fresh one.

Since we are actively using this, I definitely need to fix it for Safari 9, but I will be able to dedicate a significant time for this after mid-September.

**Comment by robertknight** [comment] 2015-08-30 14:17
Hi @pavelstudeny - Based on the information here and the xar repository, I have implemented a pure Node/JS CLI tool for creating signed xar archives: https://github.com/robertknight/xar-js . Hopefully this should be someone easier to get working on Windows as it does not depend on an OpenSSL binary being installed or a custom build of 'xar' in the path.

The actual signing part turned out to be quite straightforward using Node's crypto APIs.

**Comment by pavelstudeny** [comment] 2015-09-02 17:05
@robertknight, xar-js runs out of the box for me, so I will switch to it from car 1.6.1. But both Safari 8 and 9 keep refusing the extension. Looks like some stupid problem on my side. I will retry on a fresh machine.

**Comment by robertknight** [comment] 2015-09-03 07:33
Are you building the extension on the same Mac system you are testing on? The code should be portable as the only native code it relies on is Node's standard library but I haven't actually tested building an extension on Windows and using the result on Mac.

**Comment by robertknight** [comment] 2015-09-03 07:33
Are you building the extension on the same Mac system you are testing on? The code should be portable as the only native code it relies on is Node's standard library but I haven't actually tested building an extension on Windows and using the result on Mac.

**Comment by robertknight** [comment] 2015-09-03 07:34
Are you building the extension on the same Mac system you are testing on? The code should be portable as the only native code it relies on is Node's standard library but I haven't actually tested building an extension on Windows and using the result on Mac.

**Comment by pavelstudeny** [comment] 2015-09-03 15:31
More info at https://github.com/robertknight/xar-js/issues/1, please let me know how I can help.

**Comment by robertknight** [comment] 2015-09-03 15:39
Thanks for testing. I'll investigate when I get back home and have access to a Mac.

**Comment by pavelstudeny** [comment] 2015-10-11 17:05
Fixed by switching to https://www.npmjs.com/package/xar-js. This will be a part of 2.0 release.

**Closed as completed by pavelstudeny** 2015-10-11 17:05 UTC

**Comment by customcommander** [comment] 2015-10-12 10:21
Amazing! Thanks guys!
